### PR TITLE
Update UMD queries to match new schema for 2015-02 update

### PR DESCRIPTION
**Pull request by robinkraft**
Ready for deployment once the tables have been finalized

### CODE REVIEW

**Comment by eightysteele** [comment]
@robinkraft nice nice. once the tables are renamed (without _final extension) and we're good to go, ping me and i'll merge+deploy. sound right?

**Comment by robinkraft** [comment]
Yep.

**Comment by eightysteele** [comment]
@robinkraft @brookisme status on this PR?

**Comment by robinkraft** [comment]
Best coordinate deploy with @apercas or @d4weed - the updated UMD tables aren't live yet so these queries would fail. But they do work with the updated tables.

Maybe have a tagged release for the UMD update that you can deploy easily?

**Pull request closed without merging**
