### PR TITLE
WIP: User authentication

### PR DESCRIPTION
**Pull request by eightysteele**
This PR adds user authentication login support for #223.

- [x] twitter
- [x] google (still need to fix `gflags` missing module issue)
- [x] facebook
- [x] github
- [x] linkedin
- [ ] gfw user account

### CODE REVIEW

**Comment by dpetrovics** [comment]
Twitter login should now be working, at `/auth/twitter`. All a client has to do is link to that address - the API will handle the login process and redirect them back to the originating url. 

Everyone that has contact with the API immediately gets assigned an _eauth cookie and an entry in the Session datastore. That way we can track a guest user. Once someone authenticates (via Twitter, for example), the `user_id` in the Session datastore is changed from `none` to some number. The number links to their newly created entry in `User`, which in turn has an `auth_ids` key which links to `Key Name` in the `UserProfile` datastore. These two tables store all the information about a user that is returned by the oauth provider.

Note that Twitter currently does not seem to be returning email addresses.

Once someone has successfully authenticated via `/auth/twitter`, they can call `/user/session` to get information about their current session. We return their name, Twitter username, and email (always null for now - but I assume we'll get this info from other providers).

**Comment by eightysteele** [comment]
Boom. And the cookie set on the client side after authenticating is
`_eauth` yeah?

**Comment by dpetrovics** [comment]
Correct, that's the cookie name. If you just go to http://auth.gfw-apis.appspot.com/ you'll see it. Also: https://github.com/scotch/engineauth/blob/master/engineauth/middleware.py#L26 The value for the cookie is just the session_id and user_id serialized using securecookie: https://github.com/scotch/engineauth/blob/master/engineauth/models.py#L438

**Comment by d4weed** [comment]
Hey guys!

Just a quick comment on this. There will be times where we need to call the api trough ajax while authenticated. 

By default an ajax call doesn't send the cookies along, and it seems that the way to do this is to add 

xhrFields: {
      withCredentials: true
   }

to the ajax calls, but it also seems for that to work the server cannot return a wildcard in the Access-control-allow-origin headers, it needs to return a real domain name (and this needs to be the caller)

Any chance you can modify that header in the response so it returns the referrer domain in the Access-control-allow-origin pheasder? do you need us to send it somewhere else?

Let me know

**Comment by adammulligan** [comment]
Closing this at it's now been superseded by a different branch.

**Pull request closed without merging**
